<table>
    <tr>
        <td><{$block.orgname}></td>
        <td><{$block.org}></td>
    </tr>
    <tr>
        <td><{$block.balancename}></td>
        <td><{$block.balance}></td>
    </tr>
    <tr>
        <td><{$block.pandlname}></td>
        <td><{$block.pandl}></td>
    </tr>
    <tr>
        <td><{$block.equityname}></td>
        <td><{$block.equity}></td>
    </tr>
</table>

